language: node_js
before_cache:
  - mkdir -p /home/travis/.cache/node-yeoman-remote-cache/Talend/tools
  - 'curl -Lo master.zip https://github.com/Talend/tools/archive/master.zip'
  - unzip master.zip
  - mv tools-master /home/travis/.cache/node-yeoman-remote-cache/Talend/tools/master
cache:
  directories:
    - node_modules
    - /home/travis/.cache/
notifications:
  email: false
node_js:
  - '4'
  - '6'
before_script:
  - npm prune
  - npm update
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
