sudo: false
language: node_js
cache:
  directories:
    - $HOME/.cache
    - $HOME/.yarn-cache
    - node_modules
notifications:
  email: false
node_js:
  - "6"
before_install:
  - npm install -g yarn
install:
  - yarn
after_success:
  - npm run test:cov
  - cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage
  - rm -rf ./coverage
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
