language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - documentation
node_js:
  - "6"
before_install:
  - npm i sassdoc -g
before_script:
  - npm prune
script:
  - sassdoc src/theme -d docs/sassdoc
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `docs` directory containing demo and sassdoc
    mkdir docs
    cp example/index.html docs/index.html
    cp -R dist/* docs
    # Publish on gh-pages
    cd docs
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m 'Generate gh-pages from CI'
    git push -f -q https://frassinier:$GITHUB_API_KEY@github.com/Talend/bootstrap-theme gh-pages &> /dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
  curl -Lo travis_after_all.py https://git.io/travis_after_all
  python travis_after_all.py
  export $(cat .to_export_back) &> /dev/null
  npm run semantic-release
