name: Figma SVG icons

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      svg:
        description: The raw version of the SVG
#        required: true

jobs:
  optimize:
    runs-on: ubuntu-latest
    name: Optimize SVG icon
    steps:
      - name: Install
        run: |
          sudo add-apt-repository ppa:inkscape.dev/stable
          sudo apt update
          sudo apt install -y inkscape
          sudo apt install -y imagemagick
          sudo apt install -y potrace 
          sudo apt install -y librsvg2-bin

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org/"

      - name: Optimize
        run: |
          mkdir output
          cd output
          inkscape -V
          curl https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/cade/4ad6/94e2726787237cba336e13fbbae92db1 -o out_from_figma.svg
          inkscape -b white -w 512 -h 512 out_from_figma.svg -o out_from_figma_1.png 
          convert out_from_figma_1.png out_from_figma_1.pnm
          potrace out_from_figma_1.pnm -s -o out_from_figma_2.svg
          rsvg-convert -w 24 -h 24 --keep-aspect-ratio --dpi-x 90 --dpi-y 90 -f svg out_from_figma_2.svg -o out_from_figma_3.svg
          npx svgo out_from_figma_3.svg -o out_from_figma_4.svg

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
